version: "3"

services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017

  api:
    image: stevenxie/lattice-api
    build: ./api
    ports:
      - 3000:3000
    env_file: ./api/.env

  web:
    image: stevenxie/lattice-web
    build: ./web
    ports:
      - 8000:8000
    env_file: ./web/.env
