version: "3"

services:
  web:
    image: stevenxie/lattice-web-devcontainer
    build: ./web/.devcontainer
    volumes:
      - .:/workspace:cached
    entrypoint: ["/bin/sh", "-c"]
    command: ["while sleep 1000; do :; done"]
